// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/delivery/http/handler/handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	context "context"
	reflect "reflect"

	dto "github.com/CodeMaster482/ShortLinkAPI/internal/delivery/http/dto"
	model "github.com/CodeMaster482/ShortLinkAPI/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockLinkUsecase is a mock of LinkUsecase interface.
type MockLinkUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLinkUsecaseMockRecorder
}

// MockLinkUsecaseMockRecorder is the mock recorder for MockLinkUsecase.
type MockLinkUsecaseMockRecorder struct {
	mock *MockLinkUsecase
}

// NewMockLinkUsecase creates a new mock instance.
func NewMockLinkUsecase(ctrl *gomock.Controller) *MockLinkUsecase {
	mock := &MockLinkUsecase{ctrl: ctrl}
	mock.recorder = &MockLinkUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkUsecase) EXPECT() *MockLinkUsecaseMockRecorder {
	return m.recorder
}

// CreateShortLink mocks base method.
func (m *MockLinkUsecase) CreateShortLink(ctx context.Context, linkRequest *dto.CreateLinkRequest) (*model.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortLink", ctx, linkRequest)
	ret0, _ := ret[0].(*model.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortLink indicates an expected call of CreateShortLink.
func (mr *MockLinkUsecaseMockRecorder) CreateShortLink(ctx, linkRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortLink", reflect.TypeOf((*MockLinkUsecase)(nil).CreateShortLink), ctx, linkRequest)
}

// GetFullLink mocks base method.
func (m *MockLinkUsecase) GetFullLink(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullLink", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullLink indicates an expected call of GetFullLink.
func (mr *MockLinkUsecaseMockRecorder) GetFullLink(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullLink", reflect.TypeOf((*MockLinkUsecase)(nil).GetFullLink), ctx, token)
}
