version: '3.9'

networks:
  net:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./build/schema/:/docker-entrypoint-initdb.d/
    ports:
      - "$DB_PORT:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
    - net
  
  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - .env
    ports:
      - "$REDIS_PORT:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - net
    restart: always

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    depends_on:
      postgres: {service_healthy}
      redis: {service_healthy}
    args:
        memo: $MEMO
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - net

volumes:
  pg-data: