app:
  name: 'short-link-API'
  version: '1.0.0'

grpc:
  port: '8081'

http:
  port: '8080'
  write_timeout: 5s
  read_timeout: 10s

logger:
  log_level: 'debug'

postgres:
  pool_max: 5

service:
  host: 'localhost'
  port: 8080
  interval: 5

generator:
  alphabet: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_'
  length: 10
