app:
  name: 'film-library-API'
  version: '1.0.0'

http:
  port: '8080'
  write_timeout: 5s
  read_timeout: 10s

logger:
  log_level: 'debug'
  rollbar_env: 'film-library-API'

postgres:
  pool_max: 5

service:
  host: '127.0.0.1'
  port: 4040
  interval: 5

generator:
  alphabet: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_'
  length: 10
